// Code generated by controller generator. DO NOT EDIT.

package io_tunnel

import (
	"github.com/langgenius/dify-plugin-daemon/internal/core/session_manager"
	"github.com/langgenius/dify-plugin-daemon/pkg/utils/stream"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/datasource_entities"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/requests"
)

func DatasourceValidateCredentials(
	session *session_manager.Session,
	request *requests.RequestValidateDatasourceCredentials,
) (
	*stream.Stream[datasource_entities.DataSourceValidateCredentialsResponse], error,
) {
	return GenericInvokePlugin[requests.RequestValidateDatasourceCredentials, datasource_entities.DataSourceValidateCredentialsResponse](
		session,
		request,
		1,
	)
}

func DatasourceGetWebsiteCrawl(
	session *session_manager.Session,
	request *requests.RequestDatasourceGetWebsiteCrawl,
) (
	*stream.Stream[datasource_entities.WebsiteCrawlChunk], error,
) {
	return GenericInvokePlugin[requests.RequestDatasourceGetWebsiteCrawl, datasource_entities.WebsiteCrawlChunk](
		session,
		request,
		1,
	)
}

func DatasourceGetOnlineDocumentPages(
	session *session_manager.Session,
	request *requests.RequestDatasourceGetOnlineDocumentPages,
) (
	*stream.Stream[datasource_entities.DatasourceGetPagesResponse], error,
) {
	return GenericInvokePlugin[requests.RequestDatasourceGetOnlineDocumentPages, datasource_entities.DatasourceGetPagesResponse](
		session,
		request,
		1,
	)
}

func DatasourceGetOnlineDocumentPageContent(
	session *session_manager.Session,
	request *requests.RequestInvokeOnlineDocumentDatasourceGetContent,
) (
	*stream.Stream[datasource_entities.DataSourceResponseChunk], error,
) {
	return GenericInvokePlugin[requests.RequestInvokeOnlineDocumentDatasourceGetContent, datasource_entities.DataSourceResponseChunk](
		session,
		request,
		1,
	)
}

func DatasourceOnlineDriveBrowseFiles(
	session *session_manager.Session,
	request *requests.DatasourceOnlineDriveBrowseFilesRequest,
) (
	*stream.Stream[datasource_entities.GetOnlineDriveBrowseFilesResponse], error,
) {
	return GenericInvokePlugin[requests.DatasourceOnlineDriveBrowseFilesRequest, datasource_entities.GetOnlineDriveBrowseFilesResponse](
		session,
		request,
		1,
	)
}

func DatasourceOnlineDriveDownloadFile(
	session *session_manager.Session,
	request *requests.DatasourceOnlineDriveDownloadFileRequest,
) (
	*stream.Stream[datasource_entities.DataSourceResponseChunk], error,
) {
	return GenericInvokePlugin[requests.DatasourceOnlineDriveDownloadFileRequest, datasource_entities.DataSourceResponseChunk](
		session,
		request,
		1,
	)
}
