// Code generated by controller generator. DO NOT EDIT.

package io_tunnel

import (
	"github.com/langgenius/dify-plugin-daemon/internal/core/session_manager"
	"github.com/langgenius/dify-plugin-daemon/pkg/utils/stream"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/requests"
)

func TriggerInvokeEvent(
	session *session_manager.Session,
	request *requests.TriggerInvokeEventRequest,
) (
	*stream.Stream[requests.TriggerInvokeEventResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerInvokeEventRequest, requests.TriggerInvokeEventResponse](
		session,
		request,
		512,
	)
}

func TriggerValidateProviderCredentials(
	session *session_manager.Session,
	request *requests.TriggerValidateProviderCredentialsRequest,
) (
	*stream.Stream[requests.TriggerValidateProviderCredentialsResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerValidateProviderCredentialsRequest, requests.TriggerValidateProviderCredentialsResponse](
		session,
		request,
		1,
	)
}

func TriggerDispatchEvent(
	session *session_manager.Session,
	request *requests.TriggerDispatchEventRequest,
) (
	*stream.Stream[requests.TriggerDispatchEventResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerDispatchEventRequest, requests.TriggerDispatchEventResponse](
		session,
		request,
		512,
	)
}

func TriggerSubscribe(
	session *session_manager.Session,
	request *requests.TriggerSubscribeRequest,
) (
	*stream.Stream[requests.TriggerSubscribeResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerSubscribeRequest, requests.TriggerSubscribeResponse](
		session,
		request,
		1,
	)
}

func TriggerUnsubscribe(
	session *session_manager.Session,
	request *requests.TriggerUnsubscribeRequest,
) (
	*stream.Stream[requests.TriggerUnsubscribeResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerUnsubscribeRequest, requests.TriggerUnsubscribeResponse](
		session,
		request,
		1,
	)
}

func TriggerRefresh(
	session *session_manager.Session,
	request *requests.TriggerRefreshRequest,
) (
	*stream.Stream[requests.TriggerRefreshResponse], error,
) {
	return GenericInvokePlugin[requests.TriggerRefreshRequest, requests.TriggerRefreshResponse](
		session,
		request,
		1,
	)
}
