// Code generated by controller generator. DO NOT EDIT.

package controllers

import (
	"github.com/gin-gonic/gin"
	"github.com/langgenius/dify-plugin-daemon/internal/service"
	"github.com/langgenius/dify-plugin-daemon/internal/types/app"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/plugin_entities"
	"github.com/langgenius/dify-plugin-daemon/pkg/entities/requests"
)

func TriggerInvokeEvent(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerInvokeEventRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerInvokeEvent(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}

func TriggerValidateProviderCredentials(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerValidateProviderCredentialsRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerValidateProviderCredentials(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}

func TriggerDispatchEvent(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerDispatchEventRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerDispatchEvent(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}

func TriggerSubscribe(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerSubscribeRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerSubscribe(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}

func TriggerUnsubscribe(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerUnsubscribeRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerUnsubscribe(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}

func TriggerRefresh(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.TriggerRefreshRequest]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.TriggerRefresh(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}
